package source

import (
	"strings"
	"testing"
)

func TestIsTestPath(t *testing.T) {
	test := []string{
		"foo_test.go",
		"bar.test.ts", "widget.spec.jsx",
		"handler_test.py", "model_spec.rb",
		"lib_test.rs", "FooTest.java", "FooTest.kt",
		"test_helpers.py", // test_ prefix
		"src/test/java/com/x/C.java",
		"pkg/testdata/sample.go",
		"web/__tests__/hash.js",
		// Windows separators must classify the same as POSIX — the bug one
		// copy carried by lower-casing without normalising.
		`pkg\testdata\sample.go`,
	}
	for _, p := range test {
		if !IsTestPath(p) {
			t.Errorf("IsTestPath(%q) = false, want true", p)
		}
	}

	notTest := []string{
		"main.go", "handler.py",
		// A bare test/ tree is real source in many projects; skipping it would
		// drop findings, so it must NOT count as test code.
		"internal/test/helper.go", "lib/tests.go",
		"src/app/service.ts",
	}
	for _, p := range notTest {
		if IsTestPath(p) {
			t.Errorf("IsTestPath(%q) = true, want false — that would silently drop findings", p)
		}
	}
}

func TestIsGenerated(t *testing.T) {
	gen := []struct {
		name, in string
	}{
		{"go convention", "// Code generated by protoc. DO NOT EDIT.\npackage x"},
		{"auto-generated banner", "// AUTO-GENERATED FILE - DO NOT EDIT\nexport const x = 1"},
		{"@generated", "/* @generated */\nconst y = 2"},
		{"do not modify", "# Do Not Modify This File\nx = 1"},
		{"minified long line", `const data="` + strings.Repeat("a", 6000) + `"`},
		// A minified line past the header window must still be caught (whole-file
		// scan, not just the first 4KB).
		{"minified past header", strings.Repeat("short\n", 1000) + strings.Repeat("z", 6000)},
	}
	for _, tc := range gen {
		t.Run(tc.name, func(t *testing.T) {
			if !IsGenerated([]byte(tc.in)) {
				t.Errorf("IsGenerated should be true for %q", tc.name)
			}
		})
	}

	notGen := []string{
		"package main\n\nfunc main() {\n\tprintln(\"hi\")\n}\n",
		strings.Repeat("line of code\n", 500),
		"// A normal header comment\npackage x\n",
	}
	for _, in := range notGen {
		if IsGenerated([]byte(in)) {
			t.Errorf("IsGenerated should be false for %q", in[:min(40, len(in))])
		}
	}
}
