// Package source holds cross-analyzer classification of source files — the
// facts about a path or its contents that many analyzers need and had each been
// answering for themselves.
//
// The predicate that started it: "is this test code we should not report on?"
// It existed in four analyzers, and they had drifted — one normalised paths with
// strings.ToLower alone, so a Windows backslash path missed the test directory
// entirely; three recognised only Go test files while a fourth handled a dozen
// languages. This predicate DECIDES WHETHER FINDINGS ARE DROPPED, so a wrong or
// inconsistent answer either hides a vulnerability or floods the report with
// fixture noise. One tested implementation, here, is the fix.
package source

import "strings"

// testSuffixes are filename endings that identify test code across the languages
// nox analyses.
var testSuffixes = []string{
	"_test.go",
	".test.js", ".test.jsx", ".test.mjs", ".test.cjs",
	".test.ts", ".test.tsx",
	".spec.js", ".spec.jsx", ".spec.ts", ".spec.tsx",
	"_test.py",
	"_test.rb", "_spec.rb",
	"_test.rs",
	"test.java", "tests.java",
	"test.kt", "tests.kt",
	"test.cs", "tests.cs",
	"test.php", "tests.php",
	"test.swift", "tests.swift",
}

// testDirs are path fragments that identify a test tree. Only unambiguous ones:
// a bare `test/` is a real source directory in plenty of projects, and skipping
// it would silently drop findings rather than merely quieten fixtures.
var testDirs = []string{"testdata/", "__tests__/", "src/test/", "src/tests/"}

// IsTestPath reports whether a path is test code — a test file by name, or a
// file under a recognised test tree. Path separators are normalised to forward
// slash first, so the answer is the same on Windows and POSIX (the bug one
// copy carried by lower-casing without normalising).
func IsTestPath(p string) bool {
	// Normalise separators explicitly rather than via filepath.ToSlash, which is
	// a no-op off Windows: doing it here makes the answer identical on every OS,
	// which is the drift one copy had by lower-casing without normalising at all.
	lower := strings.ReplaceAll(strings.ToLower(p), "\\", "/")
	base := lower
	if i := strings.LastIndexByte(base, '/'); i >= 0 {
		base = base[i+1:]
	}
	for _, s := range testSuffixes {
		if strings.HasSuffix(base, s) {
			return true
		}
	}
	if strings.HasPrefix(base, "test_") {
		return true
	}
	for _, d := range testDirs {
		if strings.HasPrefix(lower, d) || strings.Contains(lower, "/"+d) {
			return true
		}
	}
	return false
}

// generatedBanners are case-insensitive markers that identify machine-generated
// or vendored source. The set is the UNION of what nox's analyzers each used to
// recognise separately: the Go convention (// Code generated ... DO NOT EDIT),
// Google/Meta's @generated, and the common "auto-generated" / "do not edit" /
// "do not modify this file" banners. Two analyzers disagreeing on what counts
// as generated meant a file suppressed by one was scanned by the other; one
// list ends that.
var generatedBanners = []string{
	"code generated by",
	"// code generated",
	"@generated",
	"auto-generated",
	"do not edit",
	"do not modify this file",
}

// maxGeneratedLineLen is the line length above which a file is treated as
// minified/bundled output rather than human-authored source.
const maxGeneratedLineLen = 5000

// generatedScanBytes bounds how far into a file the banner scan reads: a
// generated banner lives in the header, and reading the whole of a large
// bundled file to look for one is wasted work.
const generatedScanBytes = 4096

// IsGenerated reports whether content looks machine-generated — it carries a
// generated banner in its header, or it contains a minified (very long) line.
// Analyzers skip such files so a report is not flooded with findings in code no
// human wrote and no human will edit.
func IsGenerated(content []byte) bool {
	head := content
	if len(head) > generatedScanBytes {
		head = head[:generatedScanBytes]
	}
	lower := strings.ToLower(string(head))
	for _, banner := range generatedBanners {
		if strings.Contains(lower, banner) {
			return true
		}
	}
	// Minified/bundled detection scans the WHOLE file: a bundle's giant line can
	// sit past the header window.
	lineLen := 0
	for _, b := range content {
		if b == '\n' {
			lineLen = 0
			continue
		}
		lineLen++
		if lineLen > maxGeneratedLineLen {
			return true
		}
	}
	return false
}
