<?php
/**
 * DO NOT EDIT — this file is generated by the schema compiler.
 *
 * @generated
 */

// A generated banner plus a table of constant descriptors. No user input, no
// dangerous sink reads a tainted value, so a precise scanner fires nothing.

return [
    'version'   => '2.4.1',
    'checksum'  => 'a1b2c3d4e5f60718293a4b5c6d7e8f90a1b2c3d4',
    'tables'    => ['users', 'posts', 'comments'],
    'generated' => '2026-01-01T00:00:00Z',
];
