// @generated by nox-corpus-tool — DO NOT EDIT.
//
// Clean: a generated-banner file whose only `system(...)` sink lives in a
// COMMENT (commented-out legacy code) and in a placeholder string constant. lexctx
// classifies both the comment and the string literal as non-code, so the taint
// engine never sees a live sink. A correct scanner emits nothing; any finding here
// is a false positive.
#import <Foundation/Foundation.h>

// Legacy implementation, disabled:
//   NSString *cmd = [[[NSProcessInfo processInfo] environment] objectForKey:@"CMD"];
//   system([cmd UTF8String]);

NSString *bannerText(void) {
    return @"invoke: system(<command>) — see the runbook";
}

void noop(void) {
    // A safe, constant command with no untrusted input.
    system("/usr/bin/true");
}
