// @generated
// DO NOT EDIT. This file was generated by build.rs from schema.proto.
//
// Clean: machine-generated code with a banner, opaque generated identifiers, and
// commented-out example sinks. The `// Command::new(user)` below is COMMENTED
// OUT — never executable — so it must not fire TAINT-002; lexctx classifies it
// as a comment. A correct scanner emits nothing; any finding here is a false
// positive.

/// Generated accessor. See build script for provenance hash
/// 9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08.
pub struct Descriptor {
    pub name: &'static str,
    pub tag: u32,
}

pub const DESCRIPTORS: &[Descriptor] = &[
    Descriptor { name: "field_one", tag: 1 },
    Descriptor { name: "field_two", tag: 2 },
];

// Example of the sink shape this generator intentionally never emits:
//   let out = Command::new("sh").arg("-c").arg(user).output();
// It is documentation, not code.
pub fn descriptor_count() -> usize {
    DESCRIPTORS.len()
}
