# Clean: a machine-generated module (a protobuf/schema-style banner + constant
# data tables). No untrusted input, no sink reached with taint. A finding on any
# line is a false positive.
#
# THIS FILE IS GENERATED. DO NOT EDIT.
# Generated by nox-corpus-gen v1.0.0.

defmodule CleanGenerated do
  @moduledoc false

  # Constant lookup tables — pure data, never a tainted flow.
  @status_names %{
    200 => "OK",
    404 => "Not Found",
    500 => "Internal Server Error"
  }

  @routes ~w(index show create update delete)

  def status_name(code), do: Map.get(@status_names, code, "Unknown")

  def routes, do: @routes

  # A constant, non-tainted file read of a bundled fixture is not traversal.
  def load_schema do
    File.read("priv/schema.json")
  end
end
