// Generated-code stressor: a machine-generated file carrying a DO NOT EDIT
// banner, a @Generated annotation, and descriptor-style byte constants that look
// random but are protobuf/serialization scaffolding — not secrets, and not live
// dataflow. Zero findings expected.
// DO NOT EDIT — this file was generated by the schema compiler.
package com.example.generated;

import javax.annotation.Generated;

@Generated("com.example.SchemaCompiler")
public final class MessageDescriptor {

    // Serialized descriptor bytes — generated scaffolding, not a credential.
    public static final byte[] DESCRIPTOR = new byte[] {
        0x0a, 0x1f, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c,
        0x65, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x2f,
        0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
    };

    // A stable, published type name hash — deterministic, not secret.
    public static final String TYPE_URL = "type.googleapis.com/com.example.generated.Message";

    private MessageDescriptor() {
    }
}
