// @generated
// DO NOT EDIT. This file was generated by sourcery from schema.graphql.
//
// Clean: machine-generated code with a banner, opaque generated identifiers, and
// a commented-out example sink. The `// system(user)` below is COMMENTED OUT —
// never executable — so it must not fire TAINT-002; lexctx classifies it as a
// comment. A correct scanner emits nothing; any finding here is a false positive.
import Foundation

/// Generated accessor. See build script for provenance hash
/// 9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08.
struct Descriptor {
    let name: String
    let tag: Int
}

let descriptors: [Descriptor] = [
    Descriptor(name: "field_one", tag: 1),
    Descriptor(name: "field_two", tag: 2),
]

// Example of the sink shape this generator intentionally never emits:
//   let user = CommandLine.arguments[1]
//   system("run \(user)")
// It is documentation, not code.
func descriptorCount() -> Int {
    return descriptors.count
}
