<#
    DO NOT EDIT — this file is generated by build/gen-manifest.ps1.
    Any manual change will be overwritten on the next build.
#>

# A generated banner and a static manifest: constant data only, no untrusted
# input and no source→sink flow. Any finding here is a false positive.
$Manifest = @{
    Name    = "acme.tools"
    Version = "1.4.2"
    Build   = "a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0"  # git SHA, a public digest
    Files   = @("run.ps1", "lib.psm1", "manifest.psd1")
}

foreach ($f in $Manifest.Files) {
    Write-Host "packaging $f"
}
