;; DO NOT EDIT — this file is generated by `lein codegen`. Regenerate, do not
;; hand-modify. The comments below quote dangerous sinks (eval, sh, slurp) so a
;; comment-scanning rule must not flag them: prose is never executable.
(ns app.generated)

;; Example usage from the docs (a comment, not live code):
;;   (eval (:params req))          ; would be code injection if it were real
;;   (shell/sh "sh" "-c" cmd)      ; would be command injection if it were real
;;   (slurp (:params req))         ; would be path traversal if it were real

;; A generated lookup table of opcodes (inert data).
(def opcodes
  {:nop 0x00 :load 0x01 :store 0x02 :add 0x03 :sub 0x04 :jmp 0x05})

(defn describe [op]
  (get opcodes op :unknown))
