// <auto-generated>
//   This file was generated by a code generator. Do not edit by hand.
//   It exercises the scanner against generated scaffolding: nested block
//   comments, Symbol literals, and constant DTO wiring — none of which carry a
//   taint flow. A precise scanner fires nothing; any finding is a false positive.
// </auto-generated>
package generated

/* Generated model registry.
   /* A NESTED block comment — the outer comment does not close at the first
      `*/ /* it re-opens */ and the SECRET-looking token executeQuery inside it
      is prose, not code. */ */
object ModelRegistry {
  // Scala Symbol literals used as generated field tags. A leading `'` followed by
  // an identifier is a Symbol (like a Rust lifetime), NOT a runaway char literal —
  // the tokens after them must stay code and introduce no flow.
  val idField = 'id
  val nameField = 'name
  val statusField = 'status

  // A constant DTO built from literal defaults — no untrusted source, no sink.
  def defaultUser(): Map[String, String] = {
    val role = "guest"
    Map("role" -> role, "status" -> "active")
  }
}
