#!/usr/bin/perl
# Clean: machine-generated code. A DO-NOT-EDIT banner plus a generated constant
# table — the kind of file that carries high-entropy-looking tokens that are not
# secrets and static data that is never a taint flow. A finding on any line is a
# false positive.
#
# !!! DO NOT EDIT — this file is generated by tools/gen_constants.pl !!!
use strict;
use warnings;

# Generated lookup table (constant data, no untrusted input).
our %MIME_TYPES = (
    html => "text/html",
    json => "application/json",
    png  => "image/png",
    svg  => "image/svg+xml",
);

# Generated build fingerprint — a constant, not a secret.
our $BUILD_ID = "build-1a2b3c4d5e6f7890";

sub mime_for {
    my ($ext) = @_;
    return $MIME_TYPES{$ext} // "application/octet-stream";
}

1;
