// Clean: a @generated banner file with a COMMENTED-OUT command-execution sink. The
// `.execute()` and Eval.me calls below live inside comments, so lexctx marks them
// non-code and the taint engine never sees a live sink. There is no taint source
// and no live sink here; any finding is a false positive.
//
// @generated by nox-codegen — DO NOT EDIT.
package com.example.generated

// Historical note (commented-out, must NOT fire):
//   def cmd = request.getParameter("cmd")
//   "run ${cmd}".execute()
//
/* Also disabled in a block comment:
   def expr = request.getParameter("expr")
   Eval.me(expr)
*/

class GeneratedBanner {
    static final String VERSION = "1.0.0"
    static final String BUILD = "20260706T000000Z"
    static final String BANNER = "nox-generated v" + VERSION
}
