# This file is auto-generated by the schema compiler. DO NOT EDIT.
#
# Clean: a generated-code banner plus generated constants. Generated files carry
# machine-shaped identifiers and hashes that broad rules trip on; none is a
# secret or a taint flow. A finding here is a false positive.
module GeneratedSchema
  # A generated fingerprint of the schema — a public checksum, not a secret.
  SCHEMA_FINGERPRINT = "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08"

  # Generated column list — inert data.
  COLUMNS = %i[id name email created_at updated_at].freeze

  # A generated regex constant (a validation pattern), not a division or a sink.
  EMAIL_PATTERN = /\A[^@\s]+@[^@\s]+\z/
end
