//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// A generated-code banner file whose long, secret-looking constants (a resource
// blob, a base64-ish struct value) must not be flagged. Zero findings expected.
namespace Generated
{
    public static class Resources
    {
        // A long alphanumeric run that resembles an embedded secret but is a
        // generated serialized resource — a data blob, not a live credential.
        public const string RawManifest = "0a0a757365722e70726f746f120470622e7631220f0a0455736572120708016a04120200a1b2c3d4e5f60718293a4b5c6d7e8f90";

        // A base64 data-URI blob (embedded icon) — the classic FP carrier; the
        // lexctx C# verbatim-string scanner classifies it as a data blob.
        public const string Icon = @"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAC0lEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==";
    }
}
