-- Code generated by protoc-gen-lua. DO NOT EDIT.
-- Clean: a generated-code banner plus identifier-shaped constants (UUIDs, hex
-- colors, a git SHA). None of these are secrets or taint flows; a finding on any
-- line here is a false positive.

local M = {}

-- Opaque identifiers that superficially resemble high-entropy secrets but are
-- public, non-sensitive constants.
M.build_id = "550e8400-e29b-41d4-a716-446655440000"
M.commit = "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b"
M.theme = { primary = "#1a2b3c", accent = "#ff8800" }

-- A descriptor byte string emitted by the generator — data, not a live sink.
M.descriptor = "\10\4User\18\4name\18\5email"

-- A comment showing a dangerous call is not executable code:
--   os.execute(user_input)  -- this is prose, not a live sink

return M
