// Guards: generated-code suppression (Track E1).
//
// nox skips machine-generated files — clean_generated.go in the precision
// suite pins that behaviour, and it is worth keeping: generated code is not
// where a human introduces a vulnerability, and reporting it is pure noise.
//
// The hazard is that the signal is a STRING. This file is hand-written and
// carries a real command injection, but it also contains the banner text as
// data, because generating that banner is what the tool does. A suppressor
// that greps for the banner anywhere in the file, rather than requiring it in
// the leading comment block, silently deletes a real finding — and does it
// most reliably in exactly the kind of code that writes other code.
package sample

import (
	"net/http"
	"os/exec"
)

// bannerTemplate is the text this tool WRITES into files it generates. The
// file you are reading is hand-written; the banner is data, not a claim.
const bannerTemplate = "// Code generated by sample. DO NOT EDIT."

func Handle(w http.ResponseWriter, r *http.Request) {
	name := r.URL.Query().Get("name")
	_ = exec.Command("sh", "-c", "echo "+name).Run() // nox-expect: TAINT-002
	_ = bannerTemplate
}
