// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
//   protoc-gen-go v1.34.2
//   protoc        v5.27.1
// source: user.proto

// A generated-code banner file whose long, secret-looking constants (field
// descriptor bytes, a struct tag with a base64-ish value) must not be flagged.
// Zero findings expected.
package userpb

// file_user_proto_rawDesc is the serialized FileDescriptorProto — a long
// alphanumeric run that resembles an embedded secret but is generated bytes.
var fileUserProtoRawDesc = "0a0a757365722e70726f746f120470622e7631220f0a0455736572120708016a04120200"

// User mirrors a generated message with base64-looking struct tags.
type User struct {
	ID    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
}
