// Clean: a @generated banner file with a COMMENTED-OUT command-execution sink.
// The `Runtime.getRuntime().exec(...)` below lives inside comments, so lexctx marks
// it non-code and the taint engine never sees a live sink. There is no taint source
// and no live sink here; any finding is a false positive.
//
// @generated by nox-codegen — DO NOT EDIT.
package com.example.generated

// Historical note (commented-out, must NOT fire):
//   val cmd = request.getParameter("cmd")
//   Runtime.getRuntime().exec(cmd)
//
/* Also disabled in a block comment:
   val p = request.getParameter("path")
   FileInputStream(p).readBytes()
*/

object GeneratedBanner {
    const val VERSION = "1.0.0"
    const val BUILD = "20260706T000000Z"
    val banner: String = "nox-generated v" + VERSION
}
